---

- name: Check API access
  hosts: localhost
  vars_files:
    - '{{ playbook_dir }}/../../config/systems.yml'
  roles:
    - check-api-access

- name: Reinstall and start all the test instances
  hosts: localhost
  vars:
    state: 'reinstalled'
  vars_files:
    - '{{ playbook_dir }}/../../config/systems.yml'
  roles:
    - setup-environment
