---

- name: Check API access
  hosts: localhost
  connection: local
  become: false
  vars_files:
    - '{{ playbook_dir }}/../../config/systems.yml'
  roles:
    - check-api-access

- name: Stop all the test instances
  hosts: localhost
  connection: local
  become: false
  vars:
    state: 'stopped'
  vars_files:
    - '{{ playbook_dir }}/../../config/systems.yml'
  roles:
    - setup-environment
