---

- name: Check API access
  hosts: localhost
  become: false
  vars_files:
    - '{{ playbook_dir }}/../../config/systems.yml'
  roles:
    - check-api-access

- name: Create and start the test instances
  hosts: localhost
  become: false
  vars:
    state: 'started'
  vars_files:
    - '{{ playbook_dir }}/../../config/systems.yml'
  roles:
    - setup-environment
